### ISSUE TITLE
Current rinkeby problem: Solver calculates wrong price

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-open-solver#60]
We have this failing solution on rinkeby https://gnosis-dev-dfusion.s3.amazonaws.com/data/rinkeby/open-solver/results/2020-04-24/instance_5292363_2020-04-24T06%3A22%3A52.976870141%2B00%3A00/06_solution_int_valid.json .

Look at the first order.

Smart contract has this:

```
    function getExecutedSellAmount(
        uint128 executedBuyAmount,
        uint128 buyTokenPrice,
        uint128 sellTokenPrice
    ) private pure returns (uint128) {
        return
            uint256(executedBuyAmount)
                .mul(buyTokenPrice)
                .div(FEE_DENOMINATOR - 1)
                .mul(FEE_DENOMINATOR)
                .div(sellTokenPrice)
                .toUint128();
    }
```

evaluating this with the first order and price gives

```
>>> 21063493713809902 * 1248611579050715546420634236 * 1000 / 999 / 1000000000000000000
2.632644859491992e+25
```
which is larger than the orders sell amount.

I think the solver is using the wrong formula. If you swap the prices you get

```
>>> 21063493713809902 * 1000000000000000000 * 1000 / 999 / 1248611579050715546420634236
16886419.0
```

which is `execSellAmount + 1` of that order in the solution.

The correct price should be around 800889530 so that the execSellAmount matches.

**Comment by marcovc** [comment]
Hi Valentim. I wonder if you can help me reproducing the problem here. Where does this value comes from `21063493713809902` ?

**Comment by marcovc** [comment]
Nevermind. I was trying with the latest version from master, and I only got 3 matches. @josojo Is this the latest version with the economic viability order constraint enabled? If so, what was the  value passed for this parameter?

**Comment by josojo** [comment]
yeah, defintively ttag v0.0.6 was running and the variable passed for min-avg-fee-per-order was 0

**Comment by marcovc** [comment]
The instance in question is this one: https://gist.github.com/josojo/313ce02794dc999e2715b5e0b6832a27

**Comment by e00E** [comment]
> Using open-solver command `"python" "-m" "src.match" "/app/instances/2020-04-24/instance_5292363_2020-04-24T06:22:52.976870141+00:00.json" "--solution=/app/results/2020-04-24/instance_5292363_2020-04-24T06:22:52.976870141+00:00/06_solution_int_valid.json" "--min-avg-fee-per-order=0" "best-token-pair"`

**Comment by e00E** [comment]
This has been happening every batch for the rinkeby open solver for some time. So we have lots of (probably similar) instances. Sorry for not linking the instance in the OP. The link is https://gnosis-dev-dfusion.s3.amazonaws.com/data/rinkeby/open-solver/instances/2020-04-24/instance_5292387_2020-04-24T08%3A23%3A04.120587324%2B00%3A00.json .

**Comment by marcovc** [comment]
No worries, thanks a lot for reporting this and pointing towards what seems to be the problem. I'll start there!
