### ISSUE TITLE
Solving times - minAvgFeePerOrder

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-open-solver#65]
When the min-avg-fee-per-order is activated, the solving time "explodes". 

Before the activation, on current mainnet instances, we get solving times of 40 secs, but after activation, we near 2 mins.

Here is one example instance:
https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet/standard-solver/instances/2020-05-02/instance_5294687_2020-05-02T08%3A00%3A32.989596121%2B00%3A00.json

Probably, we need to check in this line, whether a solution could eventually be found by some guesstimation.
```
# If solution is economically viable, exit.
        # Hopefully, in large majority of cases this will occur in the first iteration.
        if is_economic_viable(orders, prices, fee, IntegerTraits) or is_trivial(orders):
            break

```
Maybe we can check that the solution has a higher owl burn than 1 in total and otherwise skip it anyways?

**Comment by marcovc** [comment]
What is the value currently being passed to `--min-avg-fee-per-order` ?

**Comment by josojo** [comment]
10e16 OWL
