### ISSUE TITLE
economical viable constraint causes increased runtimes

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-open-solver#71]
I tested the newest code v0.0.9 in production. Unfortunately, the execution time races again to over 3 minutes. 

Not sure how we can tackle it, but we should have e2e tests in place to test the execution time.

Possible routes are: 
- do check the economically viable constraint only on the best pair, instead of on all pairs.
- enforce a minimal trade amount per non-OWL order

**Comment by marcovc** [comment]
I just run the previously problematic instance https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet/standard-solver/instances/2020-05-02/instance_5294687_2020-05-02T08%3A00%3A32.989596121%2B00%3A00.json and it takes 12 seconds. Do you have another instance?

**Comment by marcovc** [comment]
Seems this was a false alarm. Closing.
