### ISSUE TITLE
Could not round solution (nr_exec_orders > max_nr_exec_orders)

### ISSUE THREAD

**Issue by twalth3r** [gnosis/dex-open-solver#75]
The open solver had an issue with rounding a solution for this instance:
https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet_dev/open-solver/instances/2020-08-03/instance_5321545_2020-08-03T14%3A10%3A31.561627002%2B00%3A00.json

 File "/app/open_solver/src/core/validation.py", line 41, in validate
   assert nr_exec_orders <= max_nr_exec_orders
AssertionError
(see https://gnosisinc.slack.com/archives/CQZBU9T5J/p1596463904003100)

It happened again in the subsequent batch:
https://gnosis-dev-dfusion.s3.amazonaws.com/data/mainnet_dev/open-solver/instances/2020-08-03/instance_5321546_2020-08-03T14%3A15%3A31.552265513%2B00%3A00.json

**Comment by e00E** [comment]
There was another instance of this on prod for batch 5331393.

**Comment by nlordell** [comment]
There was another instance on Rinkeby
[instance.txt](https://github.com/gnosis/dex-open-solver/files/5318734/instance.txt)

**Comment by josojo** [comment]
This morning, we got a lot of them and the error of stuck with negative utility on other solvers. Here is on [example](https://gnosis-dev-dfusion.s3.amazonaws.com/data%2Fmainnet_dev%2Fstandard-solver%2Finstances%2F2020-10-06%2Finstance_5339890_2020-10-06T06%3A55%3A32.554603482%2B00%3A00.json)

**Comment by marcovc** [comment]
> There was another instance of this on prod for batch 5331393 (2020-09-06T18:51:57.013Z )
